### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [kinoaa/k-table#1]
hi，我们近期在掘金上偶然关注到了您分享的关于前端技术方向的文章，都写的非常好，希望能与您进行课程合作，将您的优秀技术经验分享给更多正在学习编程的同学。但是 github 上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系；或者您可以直接联系我们的官方合作微信号 “shiyanloukecheng”，了解合作详情，期待您的回复。

**Comment by kinoaa** [comment]
加你微信了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kinoaa/k-table"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 中午11:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[kinoaa/k-table] 寻求课程合作 (#1)





 
hi，我们近期在掘金上偶然关注到了您分享的关于前端技术方向的文章，都写的非常好，希望能与您进行课程合作，将您的优秀技术经验分享给更多正在学习编程的同学。但是 github 上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系；或者您可以直接联系我们的官方合作微信号 “shiyanloukecheng”，了解合作详情，期待您的回复。

**Comment by kinoaa** [comment]
done
